from .deep_base import CustomBaseMetric
from typing import Dict, Any, List, Optional
import sqlparse
import re

class SQLVaibhav(CustomBaseMetric):
    """Clause-wise component match between generated and gold SQL compatible with DeepEval"""

    def __init__(self, threshold: float = 0.7):
        """
        Initialize the SQL clause-level comparison metric
        
        Args:
            threshold: Threshold for pass/fail (default: 0.7)
        """
        # Initialize CustomBaseMetric with required parameters - avoiding super() calls
        CustomBaseMetric.__init__(
            self,
            name="vaibhav",
            description="Clause-level comparison between generated and gold SQL (SELECT, WHERE, GROUP BY, ORDER BY)",
            threshold=threshold,
            csv_requires=["gold_sql"],
            runtime_requires=["generated_sql", "gold_sql"]
        )

    def extract_clause(self, sql: str, clause: str) -> str:
        """
        Extract specific clause content from SQL (naive heuristic-based)
        
        Args:
            sql: SQL query string
            clause: The clause to extract (select, from, where, etc.)
            
        Returns:
            The extracted clause content as a string
        """
        sql = sql.lower()
        pattern_dict = {
            "select": r"select (.+?) from",
            "from": r"from (.+?)( where| group by| order by|$)",
            "where": r"where (.+?)( group by| order by|$)",
            "group by": r"group by (.+?)( order by|$)",
            "order by": r"order by (.+)$"
        }
        pattern = pattern_dict.get(clause)
        if pattern:
            match = re.search(pattern, sql, re.DOTALL)
            return match.group(1).strip() if match else ""
        return ""

    def normalize_clause(self, clause: str) -> List[str]:
        """
        Normalize clause: remove whitespace, lowercase, sort elements
        
        Args:
            clause: SQL clause content
            
        Returns:
            List of normalized clause components
        """
        clause = clause.lower().strip()
        if clause == "":
            return []
        # Split by common separators
        parts = re.split(r',|\band\b|\bor\b', clause)
        return sorted([p.strip() for p in parts if p.strip()])

    def calculate(self, generated_sql: str, gold_sql: str) -> Dict[str, Any]:
        """
        Calculate clause-wise similarity between generated and gold SQL
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
            
        Returns:
            Dictionary with component-wise scores and aggregate score
        """
        try:
            clause_types = ["select", "where", "group by", "order by"]
            scores = {}

            for clause in clause_types:
                gen_clause = self.extract_clause(generated_sql, clause)
                gold_clause = self.extract_clause(gold_sql, clause)

                gen_parts = self.normalize_clause(gen_clause)
                gold_parts = self.normalize_clause(gold_clause)

                if not gold_parts and not gen_parts:
                    score = 1.0
                elif not gold_parts or not gen_parts:
                    score = 0.0
                else:
                    overlap = len(set(gen_parts) & set(gold_parts))
                    total = len(set(gold_parts) | set(gen_parts))
                    score = overlap / total

                scores[f"{clause.replace(' ', '_')}_match"] = round(score, 4)

            # Average component score
            avg_score = round(sum(scores.values()) / len(scores), 4)
            scores["score"] = avg_score  # This will be used by measure() method

            return scores

        except Exception as e:
            return {
                "score": 0.0,
                "error": str(e),
                "generated_sql": generated_sql,
                "gold_sql": gold_sql
            }
    
    def measure(self, generated_sql: str, gold_sql: str) -> None:
        """
        Measure the clause-level match and set the score
        Required by DeepEval's BaseMetric
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
        """
        result = self.calculate(
            generated_sql=generated_sql,
            gold_sql=gold_sql
        )
        self._score = result["score"]