
from .deep_base import CustomBaseMetric
import sqlite3
import os
from typing import Dict, Any, Optional, Union, List, Tuple

class SQLExecutionMatch(CustomBaseMetric):
    """Execution-based match for SQL queries compatible with DeepEval"""
    
    def __init__(self, db_root_path: str, threshold: float = 1.0):
        """
        Initialize the SQL execution match metric
        
        Args:
            db_root_path: Root path to the database files
            threshold: Threshold for pass/fail (default: 1.0 for exact match)
        """
        # Initialize CustomBaseMetric with required parameters - avoiding super() calls
        CustomBaseMetric.__init__(
            self,
            name="execution_match",
            description="Result set match between generated and reference SQL",
            threshold=threshold,
            csv_requires=["gold_sql", "db_id"],
            runtime_requires=["generated_sql", "gold_sql", "db_id"]
        )
        
        self.db_root_path = db_root_path
        
    def get_db_path(self, db_id: str) -> str:
        """Get the path to the SQLite database file"""
        path = os.path.join(self.db_root_path, db_id, f"{db_id}.sqlite")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Database {db_id} not found at {path}")
        return path
        
    def calculate(self, generated_sql: str, gold_sql: str, db_id: str) -> Dict[str, Any]:
        """
        Calculate if generated SQL produces the same results as gold SQL
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
            db_id: ID of the database to query
            
        Returns:
            Dictionary with execution_match result and additional info
        """
        try:
            db_path = self.get_db_path(db_id)
            with sqlite3.connect(db_path) as conn:
                cursor = conn.cursor()
                cursor.execute(generated_sql)
                generated_res = cursor.fetchall()
                cursor.execute(gold_sql)
                gold_res = cursor.fetchall()
                match_result = generated_res == gold_res
                
                return {
                    "score": 1.0 if match_result else 0.0,  # 1.0 for match, 0.0 for no match
                    "execution_match": match_result,
                    "generated_result": generated_res,
                    "gold_result": gold_res
                }
        except Exception as e:
            return {
                "score": 0.0,  # Execution error counts as failure
                "execution_match": False,
                "error": str(e),
                "generated_sql": generated_sql,
                "gold_sql": gold_sql
            }
    
    def measure(self, generated_sql: str, gold_sql: str, db_id: str) -> None:
        """
        Measure the execution match and set the score
        Required by DeepEval's BaseMetric
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
            db_id: ID of the database to query
        """
        result = self.calculate(
            generated_sql=generated_sql,
            gold_sql=gold_sql,
            db_id=db_id
        )
        self._score = result["score"]