# sql_judge.py
import json
import asyncio
from typing import Dict, List, Any, Optional
from llm_consortium.utils.logging import logger
from ..client_init import llm
class SQLJudge:
    """
    A class to judge SQL model outputs using an LLM.
    This acts as a judge to evaluate the quality of SQL queries generated by different models.
    """
    
    def __init__(self, client):
        """
        Initialize the SQL Judge with an LLM client.
        
        Args:
            client: The LLM client to use for evaluations
        """
        
        self.client = client
        # Default judge model to use
        self.judge_model = "gpt-4o-mini"
        
    def set_judge_model(self, model_name):
        """
        Set the judge model to use for evaluations.
        
        Args:
            model_name: Name of the model to use as judge
        """
        self.judge_model = model_name
        
    async def evaluate_model_outputs(self, evaluation_results: Dict, criteria: List[str] = None) -> Dict:
        """
        Evaluate multiple models based on their SQL output quality.
        
        Args:
            evaluation_results: The evaluation results dictionary containing model outputs
            criteria: Optional list of specific criteria to judge on
            
        Returns:
            Dictionary containing judge evaluations for each model
        """
        if not criteria:
            criteria = [
                "Column name accuracy",
                "Table usage correctness",
                "Join quality",
                "Condition correctness",
                "Query structure",
                "SQL syntax correctness",
                "Query optimization",
                "Intent understanding"
            ]
        
        judge_results = {}
        
        # Evaluate each model
        for model_name, model_data in evaluation_results.items():
            judge_results[model_name] = await self.evaluate_single_model(model_name, model_data, criteria)
            
        return judge_results
    
    async def evaluate_single_model(self, model_name: str, model_data: Dict, criteria: List[str]) -> Dict:
        """
        Evaluate a single model's SQL outputs.
        
        Args:
            model_name: Name of the model
            model_data: The model's evaluation data
            criteria: List of criteria to judge on
            
        Returns:
            Dictionary containing judge's evaluation for this model
        """
        responses = model_data.get("responses", [])
        if not responses:
            return {"error": "No responses found for evaluation"}
        
        # We'll evaluate up to 10 queries to keep the context manageable
        sample_responses = responses[:10]
        
        prompt = self._create_judge_prompt(model_name, sample_responses, criteria)
        
        try:
            judge_response = await self.client.chat(
                model=self.judge_model,  # Add the model parameter
                messages=[
                    {"role": "system", "content": "You are an expert SQL judge who evaluates the quality of SQL queries generated by different models."},
                    {"role": "user", "content": prompt}
                ]
            )
            
            # Extract the content from the response
            judge_evaluation = judge_response["content"] if isinstance(judge_response, dict) and "content" in judge_response else judge_response
            
            # Try to parse structured data if available
            try:
                # Check if the response is formatted as JSON
                if judge_evaluation.strip().startswith('{') and judge_evaluation.strip().endswith('}'):
                    structured_evaluation = json.loads(judge_evaluation)
                else:
                    # Extract any JSON block that might be in the middle of the text
                    import re
                    json_match = re.search(r'```json\n([\s\S]*?)\n```', judge_evaluation)
                    if json_match:
                        structured_evaluation = json.loads(json_match.group(1))
                    else:
                        structured_evaluation = {"qualitative_analysis": judge_evaluation}
            except json.JSONDecodeError:
                structured_evaluation = {"qualitative_analysis": judge_evaluation}
            
            return {
                "model_name": model_name,
                "evaluation": structured_evaluation,
                "raw_response": judge_evaluation
            }
            
        except Exception as e:
            logger.error(f"Error during judge evaluation: {str(e)}")
            return {"error": f"Judge evaluation failed: {str(e)}"}
    
    def _create_judge_prompt(self, model_name: str, responses: List[Dict], criteria: List[str]) -> str:
        """
        Create a prompt for the LLM judge to evaluate SQL queries.
        
        Args:
            model_name: Name of the model being evaluated
            responses: List of query responses to evaluate
            criteria: List of criteria to judge on
            
        Returns:
            String prompt for the LLM judge
        """
        criteria_str = "\n".join([f"- {c}" for c in criteria])
        
        examples_str = ""
        for i, response in enumerate(responses):
            examples_str += f"\n\nExample {i+1}:\n"
            examples_str += f"Question: {response.get('question', 'N/A')}\n"
            examples_str += f"Generated SQL: {response.get('generated_sql', 'N/A')}\n"
            examples_str += f"Gold/Reference SQL: {response.get('gold_sql', 'N/A')}\n"
            examples_str += f"Execution Match: {'Yes' if response.get('execution_match', False) else 'No'}\n"
            examples_str += f"Exact Match: {'Yes' if response.get('exact_match', False) else 'No'}"
        
        prompt = f"""
I need you to evaluate the SQL queries generated by the model '{model_name}'. 
You'll analyze the quality of the generated SQL queries compared to the reference (gold) SQL queries.

Please evaluate based on the following criteria:
{criteria_str}

For each criterion, provide a score from 1-10 and brief comments.

Below are the examples to evaluate:
{examples_str}

After reviewing these examples, please provide:
1. A score (1-10) for each criterion
2. Brief comments explaining your reasoning for each score
3. Overall strengths of the model
4. Overall weaknesses of the model
5. Summary evaluation of the model's performance
6. A final score out of 100

Format your response as JSON with the following structure:
```json
{{
  "criteria_scores": {{
    "Column name accuracy": {{
      "score": 8,
      "comments": "The model correctly identified most column names..."
    }},
    // Additional criteria with scores and comments
  }},
  "strengths": ["Strength 1", "Strength 2", ...],
  "weaknesses": ["Weakness 1", "Weakness 2", ...],
  "summary": "Overall evaluation summary...",
  "final_score": 85
}}
```
"""
        return prompt
    
    async def compare_models(self, evaluation_results: Dict, model_names: List[str]) -> Dict:
        """
        Compare multiple models side by side.
        
        Args:
            evaluation_results: The evaluation results dictionary 
            model_names: List of model names to compare
            
        Returns:
            Dictionary containing comparison results
        """
        if len(model_names) < 2:
            return {"error": "Need at least 2 models to compare"}
        
        # Filter evaluation results to include only the specified models
        filtered_results = {name: evaluation_results.get(name, {}) for name in model_names}
        
        # Create a comparison prompt
        prompt = self._create_comparison_prompt(filtered_results)
        
        try:
            comparison_response = await self.client.chat(
                model=self.judge_model,  # Add the model parameter
                messages=[
                    {"role": "system", "content": "You are an expert SQL judge comparing the performance of different SQL generation models."},
                    {"role": "user", "content": prompt}
                ]
            )
            
            # Extract the content from the response
            comparison = comparison_response["content"] if isinstance(comparison_response, dict) and "content" in comparison_response else comparison_response
            
            return {
                "comparison": comparison,
                "models_compared": model_names
            }
            
        except Exception as e:
            logger.error(f"Error during model comparison: {str(e)}")
            return {"error": f"Model comparison failed: {str(e)}"}
    
    def _create_comparison_prompt(self, model_results: Dict) -> str:
        """
        Create a comparison prompt for evaluating multiple models.
        
        Args:
            model_results: Dictionary of model results to compare
            
        Returns:
            String prompt for model comparison
        """
        models_info = ""
        for model_name, data in model_results.items():
            metrics = data.get("metrics", {})
            metrics_str = "\n".join([f"- {k}: {v}" for k, v in metrics.items() if k not in ["responses"]])
            models_info += f"\n\nModel: {model_name}\nMetrics:\n{metrics_str}"
        
        prompt = f"""
I need you to compare the following SQL generation models:
{models_info}

Please provide a detailed comparison focusing on:
1. Overall performance differences
2. Strengths and weaknesses of each model relative to others
3. Which model would be best for different types of SQL queries (simple vs complex)
4. Recommendations for when to use each model

Format your response as a detailed comparison with clear sections for each point.
Include a final verdict on which model performs best overall and why.
"""
        return prompt
    
    async def before_after_tuning_comparison(self, model_name: str, before_data: Dict, after_data: Dict) -> Dict:
        """
        Compare a model's performance before and after hyperparameter tuning.
        
        Args:
            model_name: Name of the model
            before_data: Model data before tuning
            after_data: Model data after tuning
            
        Returns:
            Dictionary containing comparison results
        """
        prompt = self._create_tuning_comparison_prompt(model_name, before_data, after_data)
        
        try:
            tuning_response = await self.client.chat(
                model=self.judge_model,  # Add the model parameter
                messages=[
                    {"role": "system", "content": "You are an expert SQL judge evaluating the impact of hyperparameter tuning on SQL model performance."},
                    {"role": "user", "content": prompt}
                ]
            )
            
            # Extract the content from the response
            comparison = tuning_response["content"] if isinstance(tuning_response, dict) and "content" in tuning_response else tuning_response
            
            return {
                "model_name": model_name,
                "tuning_impact_analysis": comparison
            }
            
        except Exception as e:
            logger.error(f"Error during tuning comparison: {str(e)}")
            return {"error": f"Tuning comparison failed: {str(e)}"}
    
    def _create_tuning_comparison_prompt(self, model_name: str, before: Dict, after: Dict) -> str:
        """
        Create a prompt for comparing model performance before and after tuning.
        
        Args:
            model_name: Name of the model
            before: Model data before tuning
            after: Model data after tuning
            
        Returns:
            String prompt for tuning comparison
        """
        before_metrics = before.get("metrics", {})
        after_metrics = after.get("metrics", {})
        
        before_metrics_str = "\n".join([f"- {k}: {v}" for k, v in before_metrics.items() if k not in ["responses"]])
        after_metrics_str = "\n".join([f"- {k}: {v}" for k, v in after_metrics.items() if k not in ["responses"]])
        
        prompt = f"""
I need you to analyze the impact of hyperparameter tuning on the model '{model_name}'.

Before tuning:
{before_metrics_str}

After tuning:
{after_metrics_str}

Please provide:
1. A detailed analysis of how tuning affected model performance
2. Which aspects of the model improved the most
3. Any aspects that may have degraded
4. An explanation of why the tuning had these effects
5. Recommendations for further tuning or improvements

Format your response as a detailed analysis with clear sections for each point above.
"""
        return prompt
# class SQLJudge:
#     """
#     A class to judge SQL model outputs using an LLM.
#     This acts as a judge to evaluate the quality of SQL queries generated by different models.
#     """
    
#     def __init__(self,client):
#         """
#         Initialize the SQL Judge with an LLM client.
        
#         Args:
#             client: The LLM client to use for evaluations
#         """
        
#         self.client = client
        
#     async def evaluate_model_outputs(self, evaluation_results: Dict, criteria: List[str] = None) -> Dict:
#         """
#         Evaluate multiple models based on their SQL output quality.
        
#         Args:
#             evaluation_results: The evaluation results dictionary containing model outputs
#             criteria: Optional list of specific criteria to judge on
            
#         Returns:
#             Dictionary containing judge evaluations for each model
#         """
#         if not criteria:
#             criteria = [
#                 "Column name accuracy",
#                 "Table usage correctness",
#                 "Join quality",
#                 "Condition correctness",
#                 "Query structure",
#                 "SQL syntax correctness",
#                 "Query optimization",
#                 "Intent understanding"
#             ]
        
#         judge_results = {}
        
#         # Evaluate each model
#         for model_name, model_data in evaluation_results.items():
#             judge_results[model_name] = await self.evaluate_single_model(model_name, model_data, criteria)
            
#         return judge_results
    
#     async def evaluate_single_model(self, model_name: str, model_data: Dict, criteria: List[str]) -> Dict:
#         """
#         Evaluate a single model's SQL outputs.
        
#         Args:
#             model_name: Name of the model
#             model_data: The model's evaluation data
#             criteria: List of criteria to judge on
            
#         Returns:
#             Dictionary containing judge's evaluation for this model
#         """
#         responses = model_data.get("responses", [])
#         if not responses:
#             return {"error": "No responses found for evaluation"}
        
#         # We'll evaluate up to 10 queries to keep the context manageable
#         sample_responses = responses[:10]
        
#         prompt = self._create_judge_prompt(model_name, sample_responses, criteria)
        
#         try:
#             judge_response = await self.client.chat(messages=[
#                 {"role": "system", "content": "You are an expert SQL judge who evaluates the quality of SQL queries generated by different models."},
#                 {"role": "user", "content": prompt}
#             ])
            
#             # Extract the content from the response
#             judge_evaluation = judge_response.content if hasattr(judge_response, 'content') else judge_response
            
#             # Try to parse structured data if available
#             try:
#                 # Check if the response is formatted as JSON
#                 if judge_evaluation.strip().startswith('{') and judge_evaluation.strip().endswith('}'):
#                     structured_evaluation = json.loads(judge_evaluation)
#                 else:
#                     # Extract any JSON block that might be in the middle of the text
#                     import re
#                     json_match = re.search(r'```json\n([\s\S]*?)\n```', judge_evaluation)
#                     if json_match:
#                         structured_evaluation = json.loads(json_match.group(1))
#                     else:
#                         structured_evaluation = {"qualitative_analysis": judge_evaluation}
#             except json.JSONDecodeError:
#                 structured_evaluation = {"qualitative_analysis": judge_evaluation}
            
#             return {
#                 "model_name": model_name,
#                 "evaluation": structured_evaluation,
#                 "raw_response": judge_evaluation
#             }
            
#         except Exception as e:
#             logger.error(f"Error during judge evaluation: {str(e)}")
#             return {"error": f"Judge evaluation failed: {str(e)}"}
    
#     def _create_judge_prompt(self, model_name: str, responses: List[Dict], criteria: List[str]) -> str:
#         """
#         Create a prompt for the LLM judge to evaluate SQL queries.
        
#         Args:
#             model_name: Name of the model being evaluated
#             responses: List of query responses to evaluate
#             criteria: List of criteria to judge on
            
#         Returns:
#             String prompt for the LLM judge
#         """
#         criteria_str = "\n".join([f"- {c}" for c in criteria])
        
#         examples_str = ""
#         for i, response in enumerate(responses):
#             examples_str += f"\n\nExample {i+1}:\n"
#             examples_str += f"Question: {response.get('question', 'N/A')}\n"
#             examples_str += f"Generated SQL: {response.get('generated_sql', 'N/A')}\n"
#             examples_str += f"Gold/Reference SQL: {response.get('gold_sql', 'N/A')}\n"
#             examples_str += f"Execution Match: {'Yes' if response.get('execution_match', False) else 'No'}\n"
#             examples_str += f"Exact Match: {'Yes' if response.get('exact_match', False) else 'No'}"
        
#         prompt = f"""
# I need you to evaluate the SQL queries generated by the model '{model_name}'. 
# You'll analyze the quality of the generated SQL queries compared to the reference (gold) SQL queries.

# Please evaluate based on the following criteria:
# {criteria_str}

# For each criterion, provide a score from 1-10 and brief comments.

# Below are the examples to evaluate:
# {examples_str}

# After reviewing these examples, please provide:
# 1. A score (1-10) for each criterion
# 2. Brief comments explaining your reasoning for each score
# 3. Overall strengths of the model
# 4. Overall weaknesses of the model
# 5. Summary evaluation of the model's performance
# 6. A final score out of 100

# Format your response as JSON with the following structure:
# ```json
# {{
#   "criteria_scores": {{
#     "Column name accuracy": {{
#       "score": 8,
#       "comments": "The model correctly identified most column names..."
#     }},
#     // Additional criteria with scores and comments
#   }},
#   "strengths": ["Strength 1", "Strength 2", ...],
#   "weaknesses": ["Weakness 1", "Weakness 2", ...],
#   "summary": "Overall evaluation summary...",
#   "final_score": 85
# }}
# ```
# """
#         return prompt
    
#     async def compare_models(self, evaluation_results: Dict, model_names: List[str]) -> Dict:
#         """
#         Compare multiple models side by side.
        
#         Args:
#             evaluation_results: The evaluation results dictionary 
#             model_names: List of model names to compare
            
#         Returns:
#             Dictionary containing comparison results
#         """
#         if len(model_names) < 2:
#             return {"error": "Need at least 2 models to compare"}
        
#         # Filter evaluation results to include only the specified models
#         filtered_results = {name: evaluation_results.get(name, {}) for name in model_names}
        
#         # Create a comparison prompt
#         prompt = self._create_comparison_prompt(filtered_results)
        
#         try:
#             comparison_response = await self.client.chat(messages=[
#                 {"role": "system", "content": "You are an expert SQL judge comparing the performance of different SQL generation models."},
#                 {"role": "user", "content": prompt}
#             ])
            
#             # Extract the content from the response
#             comparison = comparison_response.content if hasattr(comparison_response, 'content') else comparison_response
            
#             return {
#                 "comparison": comparison,
#                 "models_compared": model_names
#             }
            
#         except Exception as e:
#             logger.error(f"Error during model comparison: {str(e)}")
#             return {"error": f"Model comparison failed: {str(e)}"}
    
#     def _create_comparison_prompt(self, model_results: Dict) -> str:
#         """
#         Create a comparison prompt for evaluating multiple models.
        
#         Args:
#             model_results: Dictionary of model results to compare
            
#         Returns:
#             String prompt for model comparison
#         """
#         models_info = ""
#         for model_name, data in model_results.items():
#             metrics = data.get("metrics", {})
#             metrics_str = "\n".join([f"- {k}: {v}" for k, v in metrics.items() if k not in ["responses"]])
#             models_info += f"\n\nModel: {model_name}\nMetrics:\n{metrics_str}"
        
#         prompt = f"""
# I need you to compare the following SQL generation models:
# {models_info}

# Please provide a detailed comparison focusing on:
# 1. Overall performance differences
# 2. Strengths and weaknesses of each model relative to others
# 3. Which model would be best for different types of SQL queries (simple vs complex)
# 4. Recommendations for when to use each model

# Format your response as a detailed comparison with clear sections for each point.
# Include a final verdict on which model performs best overall and why.
# """
#         return prompt
    
#     async def before_after_tuning_comparison(self, model_name: str, before_data: Dict, after_data: Dict) -> Dict:
#         """
#         Compare a model's performance before and after hyperparameter tuning.
        
#         Args:
#             model_name: Name of the model
#             before_data: Model data before tuning
#             after_data: Model data after tuning
            
#         Returns:
#             Dictionary containing comparison results
#         """
#         prompt = self._create_tuning_comparison_prompt(model_name, before_data, after_data)
        
#         try:
#             tuning_response = await self.client.chat(messages=[
#                 {"role": "system", "content": "You are an expert SQL judge evaluating the impact of hyperparameter tuning on SQL model performance."},
#                 {"role": "user", "content": prompt}
#             ])
            
#             # Extract the content from the response
#             comparison = tuning_response.content if hasattr(tuning_response, 'content') else tuning_response
            
#             return {
#                 "model_name": model_name,
#                 "tuning_impact_analysis": comparison
#             }
            
#         except Exception as e:
#             logger.error(f"Error during tuning comparison: {str(e)}")
#             return {"error": f"Tuning comparison failed: {str(e)}"}
    
#     def _create_tuning_comparison_prompt(self, model_name: str, before: Dict, after: Dict) -> str:
#         """
#         Create a prompt for comparing model performance before and after tuning.
        
#         Args:
#             model_name: Name of the model
#             before: Model data before tuning
#             after: Model data after tuning
            
#         Returns:
#             String prompt for tuning comparison
#         """
#         before_metrics = before.get("metrics", {})
#         after_metrics = after.get("metrics", {})
        
#         before_metrics_str = "\n".join([f"- {k}: {v}" for k, v in before_metrics.items() if k not in ["responses"]])
#         after_metrics_str = "\n".join([f"- {k}: {v}" for k, v in after_metrics.items() if k not in ["responses"]])
        
#         prompt = f"""
# I need you to analyze the impact of hyperparameter tuning on the model '{model_name}'.

# Before tuning:
# {before_metrics_str}

# After tuning:
# {after_metrics_str}

# Please provide:
# 1. A detailed analysis of how tuning affected model performance
# 2. Which aspects of the model improved the most
# 3. Any aspects that may have degraded
# 4. An explanation of why the tuning had these effects
# 5. Recommendations for further tuning or improvements

# Format your response as a detailed analysis with clear sections for each point above.
# """
#         return prompt