from .base_metrics import CustomBaseMetric
from typing import Dict, Any, List

class Test1ExactMatch(CustomBaseMetric):
    """Exact match comparison for SQL queries compatible with DeepEval"""
    
    def __init__(self, threshold: float = 1.0):
        """
        Initialize the SQL exact match metric
        
        Args:
            threshold: Threshold for pass/fail (default: 1.0 for exact match)
        """
        CustomBaseMetric.__init__(
            self,
            name="test1_exact_match",
            description="Exact string match between generated and reference SQL",
            threshold=threshold,
            csv_requires=["gold_sql"],  # From CSV
            runtime_requires=["generated_sql", "gold_sql"]  # From model + CSV
        )
        
    def calculate(self, generated_sql: str, gold_sql: str) -> Dict[str, Any]:
        """
        Calculate if generated SQL exactly matches the gold SQL
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
            
        Returns:
            Dictionary with exact_match result and additional info
        """
        try:
            generated_norm = generated_sql.lower().strip()
            gold_norm = gold_sql.lower().strip()
            match_result = generated_norm == gold_norm
            
            return {
                "score": 1.0 if match_result else 0.0,  # 1.0 for match, 0.0 for no match
                "exact_match": match_result,
                "generated_sql": generated_sql,
                "gold_sql": gold_sql
            }
        except Exception as e:
            return {
                "score": 0.0,  # Error counts as failure
                "test1_exact_match": False,
                "error": str(e),
                "generated_sql": generated_sql,
                "gold_sql": gold_sql
            }
    
    def measure(self, generated_sql: str, gold_sql: str) -> None:
        """
        Measure the exact match and set the score
        Required by DeepEval's BaseMetric
        
        Args:
            generated_sql: The SQL query generated by the model
            gold_sql: The reference (correct) SQL query
        """
        result = self.calculate(
            generated_sql=generated_sql,
            gold_sql=gold_sql
        )
        self._score = result["score"]